name: Branch Policy Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source is develop
        if: github.head_ref != 'develop'
        run: |
          echo "Error: 'main' branch accepts PRs only from 'develop' branch."
          echo "Current source branch is: ${{ github.head_ref }}"
          exit 1
